import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          ></link>
          <nav className="navbar navbar-default">
            <div className="container-fluid bg-blue-500">
              <div className="navbar-header">
                <a className="navbar-brand" href="/">
                  Growth HUB Website
                </a>
              </div>
              <ul className="nav navbar-nav ">
                <li className="active">
                  <a href="/">Home</a>
                </li>
                <li>
                  <a href="/users">users</a>
                </li>
                <li>
                  <a href="/users-client">users-client</a>
                </li>
                <li>
                  <a href="/users-ORM-DB">users-ORM_DB</a>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        <div className="content">{children}</div>
        {/* children nothing but route page  */}
        <footer className="footer">
          <p>
            Growth HUB Portal
            <a href="mailto:growth@example.com" className="text-red-500 p-5">
              growth@example.com
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
//{children} prop is for root page file renders
